DOC-6464-SG2-ConfigProps
couchbaselabs/docs-sync-gateway pull request #235
Opened 2020-06-27 17:12 UTC by ibsoln

https://issues.couchbase.com/browse/DOC-6464
SG-Replicate 2.0 changes including deprecation of SGR 1.0 content.

2020-06-30 16:16 UTC, ibsoln commented
Review ready: 

Staged:  https://ibsoln.github.io/stage/h2/sync-gateway/2.8/refer/config-properties.html

Pull: https://github.com/couchbase/docs-sync-gateway/pull/235

2020-08-17 23:21 UTC, adamcfraser requested changes

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +            default: true -- replication is enabled on this database
```suggestion
            default: true -- this Sync Gateway node can be assigned sg-replicate replications for this database
```
Probably best to avoid the generic term 'replication', as that would also describe Couchbase Lite replications.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +
This looks like it can be removed.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +              This **replications** property is where you configure all SG-Replicate 2.0 replications required for this database. It comprises one or more named replication definitions.
```suggestion
              The **replications** property is where you configure all SG-Replicate 2.0 replications associated with this database. It comprises one or more named replication definitions.
```

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +              Add a *replication definition* object for each replication, allowing multiple replications to be defined for any given database.
The 'allowing multiple replications' part here seems redundant with the previous paragraph.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                These replications are not guaranteed to run on the initiating node and will instead be distributed across available nodes.
I think this overstates the importance of the adhoc=true option, and some of the language here isn't exactly accurate (it's not actually necessary/recommended to configure persistent replications using the config file - creating adhoc=false replications through the REST API is equivalent).

I think you could just add documentation to the adhoc property, stating something like:
When adhoc=true, the replication definition is removed when the replication is stopped.  This includes when a one-shot replication completes, or a continuous replication is stopped via the _replicationStatus endpoint.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +              To configure SG-Replicate 1.0 replications -- see [SG-Replicate 1.0 Replications](config-properties.html#replications).
There shouldn't be a reason to direct people to configure SG-R 1.0 replications from here, the functionality is just available for backwards compatibility.  The upgrade link makes sense though.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +              this_rep:
When specifying a replication in the config, the name of the entry in the 'replications' dictionary (i.e. this_rep) must match the replication_id property, if specified.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                      - For NEW replications, the ID to be assigned to the the replication. If no *replication_id* is specified, Sync Gateway will assign a random UUID to new replications.
As mentioned above, these defaults to the name used for the replication inside the 'replications' dictionary in the config.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                      - If **cancel=true**, this is the id of the active replication task to be cancelled.
cancel=true isn't valid via config, not sure if this property definition is being reused for REST API.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                  - For new replications -- if no `replication_id` is specified, Sync Gateway will assign a random UUID
This isn't correct - random UUID isn't assigned, this_rep is required (and is treated as replication_id).

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                  A database may be associated with more than one replication and you should add one of these objects for each replication.
Maybe clearer as '...you should add a replication definition to the 'replications' collection for each replication you wish to define.'

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                        - The revision with the longest revision history wins (so, the one with most changes and consequently the highest revision Id).
If the revision histories are of equal length, the winner is selected based on the revision ID digest.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                      }`
I feel like we probably need additional documentation (beyond the config property definition) related to writing a custom conflict resolver.  Is that planned, and if so, can we include a link here?

In particular there are some details people will need to know related to returning merged results.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                      Using complex `custom_conflict_resolver` functions can noticeably degrade performance. Use a built-in resolver whenever possible.
```suggestion
                      Using complex `custom_conflict_resolver` functions may degrade replication performance. Use a built-in resolver whenever possible.
```

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                      The mandatory `direction` property specifies whether the replication is *push*, *pull* or *push_and_pull* relative to this node.
```suggestion
                      The mandatory `direction` property specifies whether the replication is *push*, *pull* or *pushAndPull* relative to this node.
```

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                      - `push_and_pull` -- changes are both pushed-to and pulled-from the `remote` database
```suggestion
                      - `pushAndPull` -- changes are both pushed-to and pulled-from the `remote` database
```

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                      Replications created prior to version 2.8 run with `enable_delta_sync=false`
Given that this is the SG-R 2 configuration, there really aren't any replications of this type created prior to version 2.8.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                      A common value used when replicating from Sync Gateway is `sync_gateway/bychannel`. This option limits the pull replication to a specific set of channels. You can specify the re
sync_gateway/bychannel is the *only* currently supported replication filter.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                  max_backoff_time:
Need to review some details of this with @bbrks - will get back to you.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                  perf_tuning_params:
This can be removed.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                      The optional `purge_on_removal` configuration property determines, per replication, whether the removal of a `channel` triggers a purge.
```suggestion
                      The optional `purge_on_removal` configuration property determines, per replication, whether the removal of a document from the set of data being replicated triggers a purge.  The set of data being replicated can be defined by the replication filter, or by the user that is being used to authenticate to the remote.
```

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                      - Default = false -- document removals are ignored by receiving end
```suggestion
                      - Default = false -- document removals are ignored 
```

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +                          "channels":["channel.thisChannel"]
The channel name `channel.thisChannel` is a bit confusing - it looks like the `channel.` prefix is required.  I think just `thisChannel` would be preferable.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sg.yaml
> +
'username' and 'password' properties have been added to the replication config.  They can be used to specify the remote user, as an alternative to specifying them on the query string in the `remote` definition.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/examples/configuration/sync-gateway-config.json
> +// tag::icr-simple-conflict-resolver[]
It looks like these examples need to be updated to use the function(conflict) signature.

2020-08-17 23:21 UTC, adamcfraser commented on modules/ROOT/examples/configuration/sync-gateway-config.json
> +                                    console.log("full remoteDoc doc: "+JSON.stringify(mergedDoc));
It looks like the last line of logging should be 'full mergedDoc doc'.

Also, mergedDoc._rev will need to be set to "" when taking this approach.

2020-09-17 14:43 UTC, closed without merging