DOC-4216
couchbaselabs/docs-sync-gateway pull request #24
Opened 2018-11-20 08:48 UTC by jamiltz

https://issues.couchbase.com/browse/DOC-4216

2018-11-21 13:12 UTC, bbrks requested changes
I've tweaked some of the wording, and changed the units `Mb` -> `MB`.

I think GitHub lets you accept these suggestions in bulk through the web UI now if you agree.

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +|20 Mb per document
```suggestion
|20 MB per document
```

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +|1 Mb per document
```suggestion
|1 MB per document
```

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +|(20Mb - doc size) / (average channel name size * revs_limit)
```suggestion
|(20MB - doc size) / (average channel name size * revs_limit)
```

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +|1Mb / (average channel name size * revs_limit)
```suggestion
|1MB / (average channel name size * revs_limit)
```

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +2+a|*Example 1: doc size = 5 Mb, average channel name size = 25 bytes, revs_limit = 100*
```suggestion
2+a|*Example 1: doc size = 5 MB, average channel name size = 25 bytes, revs_limit = 100*
```

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +|(20Mb - 5Mb)/(25bytes * 100) = 6000
```suggestion
|(20MB - 5MB)/(25 bytes * 100) = 6000
```

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +|1Mb/(25 bytes * 100) = 400
```suggestion
|1MB/(25 bytes * 100) = 400
```

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +2+a|*Example 1: doc size = 5 Mb, average channel name size = 25 bytes, revs_limit = 1000*
```suggestion
2+a|*Example 1: doc size = 5 MB, average channel name size = 25 bytes, revs_limit = 1000*
```

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +|(20Mb - 5Mb)/(25bytes * 1000) = 600
```suggestion
|(20MB - 5MB)/(25 bytes * 1000) = 600
```

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +|1Mb/(25 bytes * 1000) = 40
```suggestion
|1MB/(25 bytes * 1000) = 40
```

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +Indeed, the sync metadata is retained for each non-leaf revision.
```suggestion
Indeed, a copy of channel metadata is retained for each revision of a document.
```

We only have one sync metadata per document, but inside that there is one copy of channel metadata per revision.

2018-11-21 13:12 UTC, bbrks commented on modules/ROOT/pages/data-routing.adoc
> +The following table estimates the allowed channel count per document according to different parameters when shared bucket access is disabled/enabled.
```suggestion
The following table estimates the channel count limits per document according to different parameters when shared bucket access is disabled/enabled.
```

2018-11-21 16:16 UTC, jamiltz commented
@bbrks great thanks.
And wow the bulk accept suggestion feature is so good.

2018-11-30 14:16 UTC, jamiltz commented
@adamcfraser, awaiting your PR approval (for correctness).

@bbrks can you OK the PR following the changes?

2018-12-07 19:27 UTC, bbrks commented
Hey @jamiltz ,

I've discussed this change with @adamcfraser and I think we're going to change tack a little bit.

We'll be improving the stats monitoring and error/warnings related to this inside Sync Gateway for the next version, and instead provide a section in the docs with a "What to do when your channel count nears/exceeds usable space" so the user can solve their problem.

The new section should describe that in order to alleviate oversized channel metadata, they should lower one or more of the following:
1. number of channels per document
2. channel name lengths
3. revs_limit

2018-12-10 15:27 UTC, jamesnocentini commented
Thanks @bbrks , updated the PR. Let me know if it needs further modifications.

2018-12-10 19:17 UTC, bbrks approved these changes
Cool, thanks for those changes @jamiltz

2018-12-11 18:45 UTC, merged