DOC-4500
couchbaselabs/docs-sync-gateway pull request #33
Opened 2018-12-10 15:03 UTC by jamiltz

https://issues.couchbase.com/browse/DOC-4500

2018-12-10 15:03 UTC, jamiltz commented
assigning @bbrks as reviewer.

2018-12-10 19:15 UTC, bbrks requested changes
New parameter takes textual log level, e.g. "info", "warn", etc.

2018-12-10 19:15 UTC, bbrks commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +      Verbosity of the logging. The default value is 1 which is regular logging. level=2 enables warnings and
The parameter was changed to accept the same textual values as the SG config. Valid options are `none`, `error`, `warn`, `info`, `debug`, `trace`:

https://github.com/couchbase/docs-sync-gateway/blob/8b15b8fbd002d17636d9099eed06780be847c6f0/modules/ROOT/pages/logging.adoc#log-levels

2019-06-20 12:17 UTC, bbrks commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +      Verbosity of the logging. The default value is 1 which is regular logging. level=2 enables warnings and
```suggestion
      Verbosity of the logging. Valid values are `none`, `error`, `warn`, `info`, `debug,` or `trace`.
```

2019-06-20 12:18 UTC, bbrks commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +    type: integer
```suggestion
    type: string```

2019-06-20 12:18 UTC, bbrks commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +      panics logging and level=3 will log panics only.
```suggestion

```

2019-06-20 12:19 UTC, bbrks requested changes
Updating with suggestions

2019-06-20 14:56 UTC, merged

2019-06-20 14:56 UTC, jamiltz commented
@bbrks Thanks!