DOC-2920
couchbaselabs/docs-sync-gateway pull request #54
Opened 2019-03-29 14:31 UTC by jamiltz

https://issues.couchbase.com/browse/DOC-2920

2019-04-14 19:26 UTC, adamcfraser requested changes
Started working through some of the items missing descriptions - will try to get to the rest in the next few days.

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Channel cache requests fully served by the cache.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Channel cache requests not fully served by the cache.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Revision cache hits.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Revision cache misses.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                  properties:
```suggestion
                  properties:
                    abandoned_seqs:
                      type: integer
                      description: The number of skipped sequences that were not found after 60 minutes and were abandoned.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                    abandoned_seqs:
abandoned_seqs is included in the cache stats - I moved it up, it can be removed from here.

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Count of instances during import when the document cas had changed, but the document body was not changed. 
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Count of DCP mutations added to Sync Gateway's channel cache.  Can be used with dcp_caching_time to monitor cache processing latency.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Time between DCP mutation arriving at Sync Gateway and being added to channel cache (aggregate).
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Number of document mutations received by Sync Gateway over DCP.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Time between document write and document being received by Sync Gateway over DCP.  If the document was written prior to Sync Gateway starting the feed, is measured as the time since the feed was started.  Can be used to monitor DCP feed processing latency.  
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      description: Count of the number of documents read via replication since Sync Gateway startup.
```suggestion
                      description: Count of the number of documents read via Couchbase Lite 2.x replication since Sync Gateway startup.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      description: Count of the number of documents read via the REST API since Sync Gateway startup.
```suggestion
                      description: Count of the number of documents read via the REST API since Sync Gateway startup. Includes Couchbase Lite 1.x replication.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Total number of bytes read via Couchbase Lite 2.x replication since Sync Gateway startup.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
Using the terminology 'Couchbase Lite 2.x replication' to describe blip/websocket-based replication.  This could expand to more than just Couchbase Lite in the future, in case you think that merits a different choice of naming.

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Total number of bytes written as part of document writes since Sync Gateway startup.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                       description: Total number of bytes written as part of Couchbase Lite 2.x document writes since Sync Gateway startup.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Number of high sequence lookups. 
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Number of unused, reserved sequences released by Sync Gateway.
```

2019-04-14 19:26 UTC, adamcfraser commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
```suggestion
                      type: integer
                      description: Number of sequences reserved by Sync Gateway.
```

2019-04-16 13:40 UTC, jamiltz commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                      type: integer
Ok noted, thanks.

2019-04-16 13:46 UTC, jamiltz commented on modules/ROOT/assets/attachments/sync-gateway-admin.yaml
> +                    abandoned_seqs:
https://github.com/couchbase/docs-sync-gateway/commit/e7342ada9bbe2d880284730a698096fa36debb62

2019-04-30 15:53 UTC, merged