DOC-10130 Errors on Sync Gateway Supported Environments Page
couchbaselabs/docs-sync-gateway pull request #702
Opened 2022-06-14 12:22 UTC by RayOffiah

https://issues.couchbase.com/browse/DOC-10130

Fixed

2022-06-14 18:16 UTC, djpongh requested changes

2022-06-14 18:16 UTC, djpongh commented on modules/ROOT/pages/_partials/sgw-supported-os.adoc
> +
this should be moved down to table 3 (need to explicitly call out Arm64 )

2022-06-15 06:49 UTC, RayOffiah commented on modules/ROOT/pages/_partials/sgw-supported-os.adoc
> +
Fixed

2022-06-15 06:52 UTC, RayOffiah commented
@djpongh 

Could you take another look at the changes? 

The page doesn't usually mention the hardware under the operating system, so it does stand out a bit.

Thanks.

2022-06-24 13:11 UTC, djpongh commented
looks good - Apple is a special case because their old systems are x86 based and the new systems are ARM64 based

2022-06-24 13:11 UTC, djpongh approved these changes

2022-06-24 13:13 UTC, merged