DOC-5184 - cobalt cache enhancement properties
couchbaselabs/docs-sync-gateway pull request #83
Opened 2019-06-11 15:02 UTC by jamiltz

https://issues.couchbase.com/browse/DOC-5184

This PR originates from the [Technical Spec](https://docs.google.com/document/d/1v60oiWY-M0qExEnWb-bvEodj76ds_qfJXoL3U_9locA/edit?ts=5cc1af33#heading=h.ry6bjo56d7j0)

<img src=https://user-images.githubusercontent.com/2589337/59282897-2d35f680-8c59-11e9-9899-35b09ed05998.png width=300/>

@adamcfraser @bbrks @JRascagneres This PR is updating the schema. Feel free to comment if you are you aware of any other config changes for Cobalt.

2019-06-13 13:01 UTC, bbrks approved these changes
I've copied the descriptions of the old config options over to the new ones, and made some small modifications based on changes that were made during development.

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +                size:
```suggestion
                size:
                  type: integer
                  description: Size of the revision cache, specified as the total number of document revisions to cache in memory for all recently accessed documents. When the revision cache is full, Sync Gateway removes less recent document revisions to make room for new document revisions. Adjust this property to tune memory consumption by Sync Gateway, for example on servers with less memory and in cases when Sync Gateway creates many new documents and/or updates many documents relative to the number of read operations.
                  default: 5000
```

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +                shard_count:
```suggestion
                shard_count:
                  type: integer
                  description: Number of shards the rev cache should be split into. More shards allows for lower cache contention when accessing distinct revisions, at the cost of some memory overhead per-shard. This generally should not greatly exceed the number of CPU threads available to Sync Gateway.
                  default: 8
```

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +                max_number:
```suggestion
                max_number:
                  type: integer
                  description: Maximum number of channel caches which will exist at any one point
                  default: 50000
```

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +                max_wait_pending:
```suggestion
                max_wait_pending:
                  type: integer
                  description: Maximum wait time in milliseconds for a pending sequence before skipping sequences.
                  default: 5000
```

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +                max_num_pending:
```suggestion
                max_num_pending:
                  type: integer
                  description: Maximum number of pending sequences before skipping the sequence.
                  default: 10000
```

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +                max_wait_skipped:
```suggestion
                max_wait_skipped:
                  type: integer
                  description: Maximum wait time in milliseconds for a skipped sequence before abandoning the sequence.
                  default: 3600000
```

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +                enable_star_channel_cache:
```suggestion
                enable_star_channel:
                  type: boolean
                  description: Enable the star (*) channel.
                  default: 'true'
```

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +                expiry:
```suggestion
                expiry_seconds:
                  type: integer
                  description: Time (seconds) to keep entries in cache beyond the minimum retained.
                  default: 60
```

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +                min_length:
```suggestion
                min_length:
                  type: integer
                  description: Minimum number of entries maintained in cache per channel.
                  default: 50
```

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +                max_length:
```suggestion
                max_length:
                  type: integer
                  description: Maximum number of entries maintained in cache per channel.
                  default: 500
```

2019-06-13 13:01 UTC, bbrks commented on modules/ROOT/assets/attachments/sg.yaml
> +              properties:
Added high/lower watermark options not in the config tech spec:

```suggestion
              properties:
                compact_high_watermark_pct:
                  type: integer
                  description: High watermark for channel cache eviction (percent)
                  default: 80
                compact_low_watermark_pct:
                  type: integer
                  description: Low watermark for channel cache eviction (percent)
                  default: 60
```

2019-06-13 13:02 UTC, bbrks requested changes
Oops. Hit wrong button for my review above.

2019-06-14 13:25 UTC, jamiltz commented
@bbrks Perfect!

I'll merge the PR to get it on https://docs-staging.couchbase.com. And we'll set up other rounds of reviews before the release.

2019-06-14 13:26 UTC, merged